# TODO: consider creating deploy --interface widget --game Explore (name or fpath) --version latest ....
# script that would build/deploy here so that people who just import the package from
# poetry/pip can run deploy without forking/cloning the repo and having to do it in actions
